Docker build args instead of file edits
jgodara/owncloud pull request #1
Opened 2019-04-24 06:37 UTC by Lewiscowles1986

Put simply this makes the python base-image a build-arg (with default so x86 build is the same), so that people are not editing code files to get this to run.

A next-step could be to make a separate docker-compose.yml for rPi users which supplies this build arg so rPi users can use docker-compose (albeit pointing at a specific file)

2019-04-24 07:32 UTC, realbucksavage requested changes
Would you be able to change the docker tag to `pymycloud`?

2019-04-24 14:32 UTC, Lewiscowles1986 commented
When I get back from work tonight I will 👍

2019-04-24 19:26 UTC, Lewiscowles1986 commented
Updated. Let me know if it's okay. I added a few more bits

2019-04-25 02:03 UTC, realbucksavage approved these changes

2019-04-25 02:03 UTC, merged

2019-04-25 02:05 UTC, jgodara commented
@Lewiscowles1986  Everything's good.

Thanks a lot for your contributions :)